#!/usr/bin/env zsh

function project () {
  local projects_dir target

  projects_dir="${PROJECTS:-~/projects}"
  if [[ -z "${1}" ]]; then
    cd "${projects_dir}"
    return 0
  fi

  target="${projects_dir}/${1}"

  if [ -d "${target}" ]; then
    cd "${target}"
    return 0
  else
    read -q "REPLY?Project ${target} doesn't exist. Create it? " -n 1 -r
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        mkdir "$target"
        cd "${target}"
        return 0
    fi
  fi

  return 1
}
