#!/usr/bin/env bash

# Exit if Homebrew is not installed.
[[ -z $(which brew) ]] && echo "Homebrew is needed here..." && return 1

# shellcheck disable=1090
source "$HOME/.brew.sh"

declare recipes=(
  'gpg'
  'pinentry-mac'
  # 'gpg-agent'

  # Install GNU core utilities (those that come with OS X are outdated)
  'coreutils'
  # Install some other useful utilities like `sponge`
  'moreutils'
  # Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
  'findutils'
  # Install GNU `sed`, overwriting the built-in `sed`
  'gnu-sed --with-default-names'
  'gzip'
  # Install Bash 4
  'bash'
  'bash-completion'

  # Install wget with IRI support
  'wget --with-iri'

  # Install more recent versions of some OS X tools
  'vim --with-override-system-vi --with-lua'
  'grep --with-default-names'
  'screen'
  'openssh'

  'htop'
  'ack'
  'jp2a'
  'zsh'
  'git'
  # 'mercurial'
  'imagemagick --with-webp'
  'pigz'
  'rename'
  'tree'
  'webkit2png'
  'zopfli'
  'ngrep'
  'hr'
  'the_silver_searcher'  # ag
  'ctags'
  'gibo'
  'tmux'
  'screen'
  'shellcheck'
  'httpie'
  # 'pgcli'
  'mycli'
  'dark-mode'
  'jq'
  'nmap'
  'nano'
  'pstree'
  'pv'
  # 'terminal-notifier'
  'wifi-password'

  # 'postgresql'
  # 'mysql'

  'python'
  'python3'
  'erlang'
  # 'go'
  # 'elixir'
  # 'elm'

  'awscli'

  'libressl'
)

declare applications=(
  'appcleaner'
  'dropbox'
  # 'firefoxdeveloperedition'
  # 'google-chrome-canary'
  # 'chromium'
  # 'opera'
  'flux'
  'imagealpha'
  'imageoptim'
  'iterm2'
  'java'
  'karabiner'
  'licecap'
  'monolingual'
  'onyx'
  'quicklook-csv'
  'quicklook-json'
  'rescuetime'
  'spectacle'
  'spotify'
  'the-unarchiver'
  'transmission'
  'visual-studio-code-insiders'
  'vlc'
  'xquartz'
  # 'virtualbox'
)

declare fonts=(
  'font-fira-code'
  'font-fira-mono'
  'font-fira-sans'
  'font-inconsolata'
  'font-input'
  'font-office-code-pro'
  'font-open-sans'
  'font-roboto-mono'
  'font-roboto-slab'
  'font-roboto'
  'font-source-code-pro'
  'font-source-sans-pro'
  'font-source-serif-pro'
  'font-ubuntu'
)


brew tap caskroom/cask
brew-tap caskroom/fonts

brew doctor

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

for recipe in "${recipes[@]}"; do
  if [ ! -z "$recipe" ]; then
    # shellcheck disable=SC2086
    brew-install-or-upgrade $recipe
  fi
done

for app in "${applications[@]}"; do
  if [ ! -z "$app" ]; then
    brew cask install --appdir="/Applications" "$app"
  fi
done

for font in "${fonts[@]}"; do
  if [ ! -z "$font" ]; then
    brew cask install "$font"
  fi
done

# Cleanup stage
brewroot="$(brew --config | awk '/HOMEBREW_PREFIX/ {print $2}')"/bin

# Fix htop permissions
if [[ "$(type -P "$brewroot"/htop)" ]] && [[ "$(stat -L -f "%Su:%Sg" "$brewroot/htop")" != "root:wheel" || ! "$(($(stat -L -f "%DMp" "$brewroot/htop") & 4))" ]]; then
  echo "Updating htop permissions..."
  sudo chown root:wheel "$brewroot/htop"
  sudo chmod u+s "$brewroot/htop"
fi

ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

# Remove outdated versions from the cellar
brew cleanup
