#!/usr/bin/env bash

if [[ -z $(command -v fish) ]]; then
    echo "[fish] fish should have been installed "
    return 1
fi

fish_bin=$(which fish)

# Setup fish as default shell
read -rp "Setup fish ($fish_bin) as the default shell ? (y/n) " -n 1
[[ $REPLY =~ ^[Yy]$ ]] && chsh -s "$fish_bin" || echo

if ! fish -c 'functions fisher' > /dev/null; then
    git clone https://github.com/jorgebucaran/fisher.git .fisher.tmp \
        && mkdir -p "$HOME/.config/fish/functions" \
        && mv .fisher.tmp/fisher.fish "$HOME/.config/fish/functions" \
        && rm -rf .fisher.tmp
fi

fish -c fisher
