#!/usr/bin/env bash

if [[ -z $(which nvm) || ! -f "$NVM_DIR/nvm.sh" ]]; then
  { (
    [[ -d "$NVM_DIR" ]] && rm -r "$NVM_DIR"
    # Use cloning instead of direct link so we always get the latest by default
    git clone https://github.com/creationix/nvm.git "$NVM_DIR"
    cd "$NVM_DIR" || exit 1
    # shellcheck disable=2046
    git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin`
  ) }
fi

# shellcheck disable=1090
. "$NVM_DIR/nvm.sh"

declare node_global_packages=(
  yarn
  brunch
)

declare node_versions=(
  stable
  lts/*
)

for version in "${node_versions[@]}"; do
  nvm install "$version"
  nvm use "$version"
  for pkg in "${node_global_packages[@]}"; do
    npm install --global --silent "$pkg"
  done
done

nvm use default
nvm alias default lts/*
