#!/usr/bin/env bash

ENV_DIR="$HOME/.pyenvs"
mkdir -p "$ENV_DIR"

declare both=(
  'ipython'
  flake8
  pylint
  bpython
)

declare python2=(
  virtualenv
)

pip2 install --upgrade setuptools pip wheel
pip install --upgrade setuptools pip wheel

pip2 install "${both[@]}" "${python2[@]}"
pip install "${both[@]}"
