#!/usr/bin/env bash

# shellcheck disable=1090
source "$HOME/.brew.sh"
export PYENV_ROOT="$HOME/.pyenv"

brew-install-or-upgrade python
brew-install-or-upgrade pyenv
brew-install-or-upgrade pyenv-virtualenv

pip install --upgrade setuptools pip wheel
