#!/usr/bin/env bash

WORKON_HOME="${WORKON_HOME:-"$HOME/.virtualenvs"}"
mkdir -p "$WORKON_HOME"

# shellcheck disable=1090
source "$HOME/.brew.sh"

brew-install-or-upgrade pyenv
# brew-install-or-upgrade pyenv-virtualenv

declare _2and3=(
  'ipython'
  flake8
  pylint
  bpython
  tox
  ipython
)

declare python2=(
  virtualenv
)

pip2 install --upgrade setuptools pip wheel
pip install --upgrade setuptools pip wheel

pip2 install "${_2and3[@]}" "${python2[@]}"
pip install "${_2and3[@]}"
