#!/usr/bin/env bash

rustup_url=https://static.rust-lang.org/rustup/dist/i686-apple-darwin/rustup-init
file="rustup-init.$$.$RANDOM"

echo "Downloading rustup from $rustup_url to $file"

curl $rustup_url -S > "$file"
chmod +x "$file"
./"$file" --no-modify-path -v -y
rm -f "$file"

rustup install stable
rustup install nightly
rustup default stable
