#!/usr/bin/env bash

# Install vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

vim --noplugin -u ~/.vim/plug.vim -N "+set hidden" "+syntax on" +PlugClean! +PlugInstall
