#!/usr/bin/env bash

# install Vundle
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
# install Vundle plugins
vim --noplugin -u ~/.vim/packages.vim -N "+set hidden" "+syntax on" +PluginClean! +PluginInstall +qall
