#!/usr/bin/env bash

origin=$(pwd)

local zsh_location
[[ -f /usr/local/bin/zsh ]] && zsh_location="/usr/local/bin/zsh" || zsh_location="/bin/zsh"

# Setup zsh as default shell
read -p "Setup zsh as the default shell ? (y/n) " -n 1
[[ $REPLY =~ ^[Yy]$ ]] && chsh -s $zsh_location || echo

cd $HOME || exit 1

git clone git@github.com:tarjoilija/zgen.git .zgen

cd "$origin" || exit 1

unset origin, zsh_location
