#!/usr/bin/env bash

echo

pip install --upgrade setuptools
pip install --upgrade pip

ENV_DIR="$HOME/.pyenvs"
mkdir -p $ENV_DIR

pip install --upgrade virtualenv
pip install --upgrade virtualenvwrapper

pip install "ipython[all]" --upgrade
