[tools]
usage = "latest"

# Python stuff
python = ["3.13", "3.12", "3.11", "3.10", "3.9",]
uv = "latest"
"pipx:nox" = { version = "latest", uvx = true, uvx_args = """\
--no-managed-python \
"""}
"pipx:keyring" = { version = "latest", uvx = true, uvx_args = """\
--no-managed-python \
"""}
"pipx:hatch" = { version = "latest", uvx = true, uvx_args = """\
--no-managed-python \
"""}

# Other languages with occasional use
node = "lts"
lua = "latest"
zig = "latest"
erlang = "latest"
elixir = "latest"
gleam = "latest"
ruby = "latest"

# Various tools where having the same version per project often matters but that are nice to have globally too.
sops = "latest"
pre-commit = "latest"
"npm:prettier" = "latest"

# LLM stuff
"npm:@anthropic-ai/claude-code" = "latest"
"pipx:aider-chat" = { version = "latest", uvx = true, uvx_args = """\
--no-managed-python
"""}
"pipx:llm" = { version = "latest", uvx = true, uvx_args = """\
--python 3.12 \
--no-managed-python \
--with llm-anthropic \
--with llm-fragments-github \
--with llm-fragments-pdf \
--with llm-fragments-site-text \
--with llm-gemini \
--with llm-mistral \
--with llm-mlx \
--with llm-ollama \
--with llm-templates-fabric \
"""}
"pipx:files-to-prompt" = { version = "latest", uvx = true, uvx_args = """\
--no-managed-python \
"""}
"pipx:shot-scraper" = { version = "latest", uvx = true, uvx_args = """\
--no-managed-python \
"""}
"npm:@sourcegraph/amp" = "latest"
"npm:@google/gemini-cli" = "latest"

# Cloud and infra stuff
"asdf:mise-plugins/mise-gcloud" = "latest"
"aqua:aws/aws-cli" = "latest"

[settings]
paranoid = false
disable_default_shorthands = true

not_found_auto_install = false
idiomatic_version_file_enable_tools = ["python", "node", "ruby"]
