#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

gem update

gem install pry
gem install rails
gem install sass
gem install awesome_print
gem install jekyll
gem install s3_website
