#!/usr/bin/env bash

# Install NVM latest
current=$(pwd)
git clone https://github.com/creationix/nvm.git ~/.nvm
cd ~/.nvm
git checkout `git describe --abbrev=0 --tags`
cd $current
unset current

# Make sure we’re using the latest npm and update existing packages
npm update

npm install -g grunt-cli
npm install -g gulp
npm install -g bower
npm install -g yo
npm install -g mocha
npm install -g istanbul
npm install -g browserify
npm install -g gitignore
