#!/usr/bin/env bash

# install Vundle
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle/
# install Vundle plugins
vim --noplugin -u ~/.vim/vundles.vim -N "+set hidden" "+syntax on" +BundleClean! +BundleInstall +qall
